const courses = [
  {
    id: '1',
    language: 'C++',
    field: 'Backend',
    price: '$100',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg',
    details: 'This course covers the fundamentals of C++ programming and its applications in backend development. Before starting this course, it is recommended to have basic knowledge of programming concepts such as variables, loops, and functions. Familiarity with object-oriented programming (OOP) principles will also be beneficial. You should have a C++ compiler and a suitable Integrated Development Environment (IDE) installed on your computer for practice. Be prepared to work on coding exercises and projects to reinforce your learning and gain hands-on experience with C++ development.',
  },
  {
    id: '2',
    language: 'Java',
    field: 'DevOps',
    price: '$120',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/30/Java_programming_language_logo.svg',
    details: 'This course focuses on Java programming for DevOps. Before enrolling in this course, you should have a good understanding of Java fundamentals, including variables, data types, and control structures. Knowledge of object-oriented programming (OOP) concepts is crucial. Additionally, familiarity with build tools like Maven and version control systems like Git will be beneficial for your DevOps journey. Expect to work on real-world projects and collaborate with others to simulate the DevOps environment and best practices.',
  },
  {
    id: '3',
    language: 'Python',
    field: 'Mobile Development',
    price: '$90',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg',
    details: 'This course covers Python programming for Mobile Development. Before starting this course, you should have a basic understanding of Python syntax, data structures, and functions. Knowledge of object-oriented programming (OOP) will also be helpful. Aspiring mobile developers should have some familiarity with mobile app development frameworks like React Native or Flutter. Expect to work on hands-on projects where you will build mobile applications and learn about the unique challenges and considerations in mobile development using Python.',
  },
  {
    id: '4',
    language: 'Javascript',
    field: 'Front-end',
    price: '$80',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png',
    details: 'This course focuses on JavaScript programming for front-end web development. Before enrolling in this course, you should have a solid understanding of HTML and CSS as JavaScript is primarily used to enhance the interactivity and functionality of web pages. Familiarity with basic programming concepts like variables, loops, and functions is essential. Additionally, knowledge of DOM manipulation and asynchronous programming (callbacks, promises, async/await) will be beneficial. Prepare to work on interactive web projects to apply your JavaScript skills and create engaging user experiences.',
  },
  {
    id: '5',
    language: 'C',
    field: 'Systems Programming',
    price: '$95',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/1/19/C_Logo.png',
    details: 'This course focuses on C programming for systems development. C is a powerful programming language used for developing operating systems, embedded systems, and low-level software. Before taking this course, you should have a good understanding of basic programming concepts like variables, loops, and functions. Familiarity with pointers and memory management is essential for systems programming in C. Expect to work on projects that involve interacting with hardware and optimizing performance in resource-constrained environments.',
  },
  {
    id: '6',
    language: 'C#',
    field: 'Game Development',
    price: '$110',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/C_Sharp_wordmark.svg',
    details: 'This course focuses on C# programming for game development using popular game engines like Unity. Prior knowledge of C# fundamentals, including variables, data types, and control structures, is necessary. Understanding object-oriented programming (OOP) concepts will be highly beneficial, as game development heavily relies on OOP principles. During this course, you will work on creating your own games, implementing mechanics, and integrating assets to build immersive gaming experiences.',
  },
  {
    id: '7',
    language: 'Swift',
    field: 'iOS App Development',
    price: '$130',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Swift_logo.svg',
    details: 'This course covers Swift programming for iOS app development. Swift is the primary programming language for building applications on Apple\'s iOS platform. Before enrolling in this course, you should have a basic understanding of Swift syntax, data structures, and functions. Knowledge of object-oriented programming (OOP) will also be helpful. Expect to work on hands-on projects where you will create iOS apps, leverage Apple\'s frameworks, and learn about the best practices in iOS development.',
  },
  {
    id: '8',
    language: 'Ruby',
    field: 'Web Development',
    price: '$95',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Ruby_logo.svg',
    details: 'This course focuses on Ruby programming for web development. Ruby is known for its simplicity and productivity, making it a popular choice for building web applications. Before starting this course, you should have a basic understanding of Ruby syntax, variables, and control structures. Familiarity with object-oriented programming (OOP) concepts will be beneficial. During the course, you will work on building web applications using Ruby on Rails and gain insights into web development best practices.',
  },
  {
    id: '9',
    language: 'Go',
    field: 'Cloud Services',
    price: '$115',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
    details: 'This course covers Go programming for cloud services and distributed systems. Go, also known as Golang, is a language designed for concurrency and scalability, making it suitable for cloud-based applications. Before enrolling in this course, you should have a solid understanding of basic programming concepts and some experience with another programming language. Familiarity with concurrent programming will be beneficial. Expect to work on projects that involve building scalable and efficient cloud services using Go.',
  },
  {
    id: '10',
    language: 'PHP',
    field: 'Back-end Web Development',
    price: '$85',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/27/PHP-logo.svg',
    details: 'This course focuses on PHP programming for back-end web development. PHP is a widely-used server-side language for creating dynamic and interactive web applications. Before starting this course, you should have a basic understanding of PHP syntax, data handling, and functions. Familiarity with databases and SQL will also be helpful. During the course, you will work on building web applications and RESTful APIs using PHP and gain knowledge of best practices in back-end web development.',
  },
];

export default courses;
